import {lazy,Suspense,useEffect,useState} from 'react';
import {ChevronDown,ChevronRight,ChevronLeft,RefreshCw,Target,Users,ArrowUpRight} from 'lucide-react';
import {PageHeader,SEITEN_RAND,Button,Modal,inputSized,cn} from './ui-kit';
import {LoadError} from './LoadError';
import {getActivityReport,saveActivityTargets,reportMetrics,metricLabels,zeroCounts,reportPreset,shiftReportDay,type ActivityReport,type ReportGoals,type ReportMetric,type Counts} from '../utils/crmReports';
const Inventory=lazy(()=>import('./LeadInventoryReport').then(m=>({default:m.LeadInventoryReport})));
const formatDay=(day:string)=>new Date(day+'T12:00:00Z').toLocaleDateString('de-DE',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',year:'numeric'});
const number=(n:number)=>n.toLocaleString('de-DE');
function GoalEditor({goals,onClose,onSaved}:{goals:ReportGoals;onClose:()=>void;onSaved:()=>void}){
 const [form,setForm]=useState(goals),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const valid=form.workdays.length>0&&reportMetrics.every(k=>form.targets[k]===null||(Number.isInteger(form.targets[k])&&form.targets[k]!>=0&&form.targets[k]!<=100000));
 async function save(){if(saving||!valid)return;setSaving(true);setError('');try{await saveActivityTargets(form);onSaved();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <Modal title="Tagesziele festlegen" subtitle="Nur Fecat kann diese Werte bearbeiten." size="md" onClose={()=>{if(!saving)onClose();}} footer={<div className="flex w-full justify-end gap-2"><Button variant="ghost" disabled={saving} onClick={onClose}>Abbrechen</Button><Button disabled={saving||!valid} onClick={()=>void save()}>{saving?'Wird gespeichert …':'Ziele speichern'}</Button></div>}>
  <p className="mb-4 text-sm text-text-secondary">Ziel pro aktivem Mitarbeiter und Arbeitstag. Team- und Wochenziele werden daraus berechnet. Ein leeres Feld bedeutet: kein Ziel gesetzt.</p>
  <div className="grid grid-cols-2 gap-4">{reportMetrics.map(k=><label key={k} className="space-y-1 text-sm"><span>{metricLabels[k]}</span><input aria-label={'Tagesziel '+metricLabels[k]} className={inputSized} type="number" min="0" max="100000" step="1" disabled={saving} value={form.targets[k]??''} placeholder="Noch offen" onChange={e=>setForm({...form,targets:{...form.targets,[k]:e.target.value===''?null:Number(e.target.value)}})}/></label>)}</div>
  <fieldset className="mt-5"><legend className="mb-2 text-sm font-medium">Arbeitstage</legend><div className="flex flex-wrap gap-3">{[[1,'Mo'],[2,'Di'],[3,'Mi'],[4,'Do'],[5,'Fr'],[6,'Sa'],[0,'So']].map(([day,label])=><label key={day} className="flex items-center gap-1.5 text-sm"><input type="checkbox" disabled={saving} checked={form.workdays.includes(Number(day))} onChange={e=>setForm({...form,workdays:e.target.checked?[...form.workdays,Number(day)]:form.workdays.filter(d=>d!==Number(day))})}/>{label}</label>)}</div></fieldset>
  {error&&<p role="alert" className="mt-4 text-sm text-status-danger">{error}</p>}
 </Modal>;
}
function MetricCell({amount,target}:{amount:number;target:number|null}){
 const progress=target&&target>0?Math.min(100,amount/target*100):0;
 return <td className="min-w-[94px] px-3 py-4 text-right align-top tabular-nums"><span className="text-base font-semibold text-text-primary">{number(amount)}</span>{target!==null&&<><span className="ml-1 text-[11px] text-text-muted">/ {number(target)}</span>{target>0&&<div className="ml-auto mt-1.5 h-1 w-14 overflow-hidden rounded-full bg-elevated"><div className={cn('h-full rounded-full',amount>=target?'bg-status-success':'bg-accent-500')} style={{width:progress+'%'}}/></div>}</>}</td>;
}
export function ActivityReportsView(){
 const [tab,setTab]=useState<'activity'|'inventory'>('activity'),[range,setRange]=useState(()=>reportPreset('week')),[owner,setOwner]=useState('all');
 const [data,setData]=useState<ActivityReport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tick,setTick]=useState(0),[editing,setEditing]=useState(false),[expanded,setExpanded]=useState<string|null>(null);
 useEffect(()=>{if(tab!=='activity')return;const controller=new AbortController();setLoading(true);setError('');
  if(!range.from||!range.to||range.from>range.to){setLoading(false);setError('Bitte einen gültigen Zeitraum auswählen.');return;}
  const timer=setTimeout(()=>{getActivityReport(range.from,range.to,controller.signal).then(result=>{if(!controller.signal.aborted)setData(result);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},180);
  return()=>{clearTimeout(timer);controller.abort();};
 },[range.from,range.to,tick,tab]);
 const selected=data?.members.find(p=>p.id===owner),counts=selected?.counts??data?.totals??zeroCounts();
 const activeCount=data?.members.filter(p=>p.active).length??0;
 const targets=(days:number,people:number)=>(metric:ReportMetric)=>!data||data.goals.targets[metric]===null?null:data.goals.targets[metric]!*days*people;
 const scopePeople=selected?(selected.active?1:0):activeCount,periodTarget=(metric:ReportMetric)=>selected&&!selected.active?null:targets(data?.workdayCount??0,scopePeople)(metric);
 function shift(direction:number){const span=Math.round((Date.parse(range.to)-Date.parse(range.from))/86400000)+1;if(span>0)setRange({from:shiftReportDay(range.from,direction*span),to:shiftReportDay(range.to,direction*span)});}
 function exportCsv(){if(!data)return;const rows=[['Datum','Mitarbeiter',...reportMetrics.map(k=>metricLabels[k])],...data.days.flatMap(day=>(selected?[selected]:data.members).map(member=>{const c=day.members.find(m=>m.id===member.id)?.counts??zeroCounts();return [day.day,member.name,...reportMetrics.map(k=>String(c[k]))];}))];const safe=(s:string)=>'"'+(/^[=+\-@]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Partsunion-Bericht-${data.from}-${data.to}.csv`;a.click();URL.revokeObjectURL(url);}
 return <div className={cn(SEITEN_RAND,'space-y-5')}>
  <PageHeader title="Berichte" subtitle="Tagesleistung, Teamvergleich und Ziele."/>
  <nav className="flex gap-5 border-b border-border-subtle text-sm" aria-label="Berichtsart">{[['activity','Team & Aktivitäten'],['inventory','Pipeline-Bestand']].map(([key,label])=><button key={key} className={cn('border-b-2 pb-3 font-medium',tab===key?'border-accent-500 text-accent-500':'border-transparent text-text-muted')} onClick={()=>setTab(key as typeof tab)}>{label}</button>)}</nav>
  {tab==='inventory'?<Suspense fallback={<p role="status">Bestandsauswertung wird geladen …</p>}><Inventory/></Suspense>:<>
   <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-1">{([['today','Heute'],['yesterday','Gestern'],['week','Diese Woche'],['lastWeek','Letzte Woche'],['month','Dieser Monat']] as const).map(([key,label])=>{const p=reportPreset(key);return <Button key={key} size="sm" variant={p.from===range.from&&p.to===range.to?'secondary':'ghost'} onClick={()=>setRange(p)}>{label}</Button>;})}</div><div className="flex items-center gap-1"><Button size="sm" variant="ghost" aria-label="Vorheriger Zeitraum" onClick={()=>shift(-1)}><ChevronLeft className="size-4"/></Button><Button size="sm" variant="ghost" aria-label="Nächster Zeitraum" onClick={()=>shift(1)}><ChevronRight className="size-4"/></Button><Button size="sm" variant="ghost" disabled={loading} aria-label="Bericht aktualisieren" onClick={()=>setTick(v=>v+1)}><RefreshCw className={cn('size-4',loading&&'animate-spin')}/></Button></div></div>
   <div className="flex flex-wrap items-end gap-3 border-b border-border-subtle pb-5"><label className="space-y-1 text-xs text-text-muted">Von<input aria-label="Bericht von" type="date" className={inputSized} value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></label><label className="space-y-1 text-xs text-text-muted">Bis<input aria-label="Bericht bis" type="date" className={inputSized} value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></label><label className="min-w-48 space-y-1 text-xs text-text-muted">Ansicht<select aria-label="Bericht für" className={inputSized} value={owner} onChange={e=>{setOwner(e.target.value);setExpanded(null);}}><option value="all">Gesamtes Team</option>{data?.members.map(m=><option key={m.id} value={m.id}>{m.name}{m.active?'':' · inaktiv'}</option>)}</select></label><div className="ml-auto flex gap-2">{data?.canEditTargets&&<Button variant="outline" size="sm" disabled={loading} onClick={()=>setEditing(true)}><Target className="size-4"/>Zielwerte</Button>}<Button variant="ghost" size="sm" disabled={!data||loading||!!error} onClick={exportCsv}>CSV exportieren<ArrowUpRight className="size-3.5"/></Button></div></div>
   {error?<LoadError message={error} onRetry={()=>setTick(v=>v+1)}/>:loading?<div role="status" className="py-16 text-center text-sm text-text-muted">Aktivitäten werden ausgewertet …</div>:data&&<>
    <div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="flex items-center gap-2 text-lg font-semibold"><Users className="size-4 text-accent-500"/>{selected?.name??'Gesamtes Team'}</h2><p className="text-xs text-text-muted">{formatDay(data.from)} – {formatDay(data.to)} · {data.workdayCount} Arbeitstage · Europe/Berlin</p></div>
    <section aria-label="Aktivitäten im Zeitraum" className="grid grid-cols-2 gap-y-5 border-b border-border-subtle pb-5 sm:grid-cols-4">{(['processed','contacted','emails','qualified'] as const).map((k,i)=><div key={k} className={cn('px-4',i>0&&'sm:border-l sm:border-border-subtle')}><span className="text-xs text-text-secondary">{k==='processed'?'Leads bearbeitet':metricLabels[k]}</span><div className="mt-1 text-3xl font-semibold tracking-tight tabular-nums">{number(counts[k])}</div><p className="mt-1 text-xs text-text-muted">{periodTarget(k)===null?'Ziel noch offen':`Ziel ${number(periodTarget(k)!)} im Zeitraum`}</p></div>)}</section>
    {Object.values(counts).every(value=>value===0)&&<p className="text-sm text-text-muted">In diesem Zeitraum sind noch keine Aktivitäten für diese Auswahl protokolliert.</p>}
    <section className="overflow-hidden rounded-lg border border-border-subtle"><div className="flex flex-wrap items-baseline justify-between gap-2 px-4 py-3"><h3 className="text-sm font-semibold">Leistung im Zeitraum</h3><span className="text-xs text-text-muted">Ist / aktuelles Ziel · Tagesziele pro aktivem Mitarbeiter</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><ReportHeaders label="Mitarbeiter"/><tbody>
     {!selected&&<tr className="border-b border-border-subtle bg-accent-500/5"><th className="px-4 py-4 text-left">Gesamtes Team</th>{reportMetrics.map(k=><MetricCell key={k} amount={data.totals[k]} target={periodTarget(k)}/>)}</tr>}
     {(selected?[selected]:data.members).map(member=><tr key={member.id} className="border-b border-border-subtle last:border-0 hover:bg-elevated/30"><th className="px-4 py-4 text-left font-medium"><button className="text-left hover:text-accent-500" onClick={()=>setOwner(member.id)}>{member.name}</button>{!member.active&&<span className="ml-2 text-xs text-text-muted">inaktiv</span>}</th>{reportMetrics.map(k=><MetricCell key={k} amount={member.counts[k]} target={member.active?targets(data.workdayCount,1)(k):null}/>)}</tr>)}
    </tbody></table></div></section>
    <section><div className="mb-3 flex items-baseline justify-between gap-2"><h3 className="font-semibold">Tag für Tag</h3><span className="text-xs text-text-muted">{selected?'Persönliche Tagesleistung':'Tag aufklappen für alle Mitarbeiter'}</span></div><div className="overflow-x-auto rounded-lg border border-border-subtle"><table className="w-full text-sm"><ReportHeaders label="Tag / Mitarbeiter"/><tbody>{data.days.filter(day=>day.day<=(data.today||data.to)).slice().reverse().map(day=>{
     const working=data.goals.workdays.includes(new Date(day.day+'T12:00:00Z').getUTCDay()),daily=selected?day.members.find(m=>m.id===selected.id)?.counts??zeroCounts():day.counts;
     return <DayRows key={day.day} day={day.day} counts={daily} goals={targets(working?1:0,scopePeople)} open={!selected&&expanded===day.day} onToggle={()=>setExpanded(expanded===day.day?null:day.day)} expandable={!selected} members={data.members} memberCounts={day.members} memberGoal={targets(working?1:0,1)}/>;
    })}</tbody></table></div></section>
    <details className="text-xs leading-6 text-text-muted"><summary className="cursor-pointer font-medium text-text-secondary">Was wird gezählt?</summary><div className="mt-2 max-w-4xl space-y-1"><p>Bearbeitet: unterschiedliche Leads mit protokollierter Aktivität, CRM-Anruf oder gespeicherter Stammdatenänderung. Kontaktiert: unterschiedliche Leads mit protokolliertem Kontaktversuch (Anruf, E-Mail, Gespräch oder Phase „Kontaktiert“); das bedeutet nicht automatisch erreicht.</p><p>Rufnummern: unterschiedliche ausgehend gewählte Nummern mit bestätigtem Telefonie-Vorgang. E-Mails: versendete und manuell protokollierte E-Mails einschließlich Broschürenversand. Auch ein Wechsel in die Phase „Broschüre“ zählt als E-Mail; je Lead, Mitarbeiter und Tag einmal und nur, wenn an diesem Tag keine E-Mail protokolliert wurde. Qualifiziert: unterschiedliche Leads mit protokolliertem Wechsel in die Phase „Qualifiziert“. Termine: bestätigte Qualifizierungs-/Sales-Termine. Sales Calls: abgeschlossene Sales-Termine. Abschlüsse: erster dokumentierter Gewinn je Lead.</p><p>Es zählt der handelnde Mitarbeiter zum Zeitpunkt der Aktivität. Leads und Nummern werden für Team, Mitarbeiter und Zeitraum jeweils getrennt dedupliziert; Tages- und Mitarbeiterzahlen deshalb nicht einfach addieren. Alte Stammdatenänderungen ohne Bearbeiterprotokoll können nicht rückwirkend zugeordnet werden. Archivierte Leads bleiben in ihrer Historie enthalten.</p><p>Ziele zeigen die aktuell von Fecat gesetzten Tageswerte × ausgewählte Arbeitstage × aktive Mitarbeiter. Sie sind keine historischen Zielvereinbarungen. Leere Zielwerte bleiben offen.</p></div></details>
   </>}
  </>}
  {editing&&data&&<GoalEditor goals={data.goals} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);setTick(v=>v+1);}}/>}
 </div>;
}
function ReportHeaders({label}:{label:string}){return <thead className="border-y border-border-subtle bg-elevated/40 text-xs text-text-secondary"><tr><th className="min-w-48 px-4 py-3 text-left font-medium">{label}</th>{reportMetrics.map(k=><th key={k} className="whitespace-nowrap px-3 py-3 text-right font-medium">{metricLabels[k]}</th>)}</tr></thead>;}
function DayRows({day,counts,goals,open,onToggle,expandable,members,memberCounts,memberGoal}:{day:string;counts:Counts;goals:(k:ReportMetric)=>number|null;open:boolean;onToggle:()=>void;expandable:boolean;members:ActivityReport['members'];memberCounts:{id:string;counts:Counts}[];memberGoal:(k:ReportMetric)=>number|null}){
 return <><tr className="border-t border-border-subtle hover:bg-elevated/30"><th className="px-4 py-3 text-left font-medium">{expandable?<button aria-expanded={open} className="flex items-center gap-2 whitespace-nowrap" onClick={onToggle}>{open?<ChevronDown className="size-3.5"/>:<ChevronRight className="size-3.5"/>}{formatDay(day)}</button>:formatDay(day)}</th>{reportMetrics.map(k=><MetricCell key={k} amount={counts[k]} target={goals(k)}/>)}</tr>{open&&members.map(member=>{const c=memberCounts.find(m=>m.id===member.id)?.counts??zeroCounts();return <tr key={member.id} className="border-t border-border-subtle bg-elevated/30"><th className="py-3 pl-10 pr-4 text-left text-xs font-normal text-text-secondary">{member.name}</th>{reportMetrics.map(k=><MetricCell key={k} amount={c[k]} target={member.active?memberGoal(k):null}/>)}</tr>;})}</>;
}
