import '@testing-library/jest-dom/vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {CallbackPlanner,useCallbackPlanner} from './CallbackPlanner';
const mocks=vi.hoisted(()=>({save:vi.fn(),verify:vi.fn(),review:{loading:false,error:false,conflicts:[] as unknown[],confirmed:false}}));
vi.mock('../utils/storage',()=>({saveCrmCallback:mocks.save}));
vi.mock('../utils/useAppointmentConflicts',()=>({useAppointmentConflicts:()=>({...mocks.review,verify:mocks.verify})}));
vi.mock('./AppointmentConflictReview',()=>({AppointmentConflictReview:()=>null}));
const saved=vi.fn(),close=vi.fn();
function Harness(){const controller=useCallbackPlanner({leadId:"lead",assigneeId:"actor",onSaved:saved,enabled:true});return <CallbackPlanner controller={controller} admins={[{id:"actor",username:"Aaron",name:"Aaron Vogt",email:"aaron@example.test"}]} onClose={close}/>;}
function mount(){return render(<Harness/>);}
beforeEach(()=>{vi.clearAllMocks();mocks.save.mockResolvedValue({appointment:{id:'saved'}});mocks.verify.mockResolvedValue(true);mocks.review={loading:false,error:false,conflicts:[],confirmed:false};});
afterEach(cleanup);
it('does not create a callback merely by opening and needs no save button',()=>{mount();expect(screen.queryByRole('button',{name:'Rückruf planen'})).not.toBeInTheDocument();expect(mocks.save).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Schließen'}));expect(close).toHaveBeenCalledOnce();});
it('autosaves changed values, then updates the same callback without a discard prompt',async()=>{const confirm=vi.spyOn(window,'confirm');mount();fireEvent.change(screen.getByLabelText('Rückrufuhrzeit'),{target:{value:'14:15'}});await screen.findByText('Automatisch gespeichert',{}, {timeout:2500});expect(mocks.save.mock.calls[0][2].start).toMatch(/T14:15$/);const id=mocks.save.mock.calls[0][1];fireEvent.change(screen.getByLabelText('Rückrufnotiz'),{target:{value:'Lagerübersicht besprechen'}});await waitFor(()=>expect(mocks.save).toHaveBeenCalledTimes(2),{timeout:2500});expect(mocks.save.mock.calls[1][1]).toBe(id);expect(mocks.save.mock.calls[1][2].notes).toBe('Lagerübersicht besprechen');await screen.findByText('Automatisch gespeichert');fireEvent.click(screen.getByRole('button',{name:'Schließen'}));expect(confirm).not.toHaveBeenCalled();confirm.mockRestore();});
it('serializes writes and saves edits made during an in-flight request',async()=>{let resolve!:(value:unknown)=>void;mocks.save.mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));mount();fireEvent.change(screen.getByLabelText('Rückrufnotiz'),{target:{value:'Erste Notiz'}});await waitFor(()=>expect(mocks.save).toHaveBeenCalledOnce(),{timeout:2500});fireEvent.change(screen.getByLabelText('Rückrufnotiz'),{target:{value:'Neuere Notiz'}});resolve({appointment:{}});await waitFor(()=>expect(mocks.save).toHaveBeenCalledTimes(2),{timeout:2500});expect(mocks.save.mock.calls[1][2].notes).toBe('Neuere Notiz');expect(mocks.save.mock.calls[1][1]).toBe(mocks.save.mock.calls[0][1]);});
it('retains an unsuccessful draft and retries with its original UUID',async()=>{mocks.save.mockRejectedValueOnce(new Error('Verbindung unterbrochen'));mount();fireEvent.click(screen.getByRole('button',{name:'Morgen'}));await screen.findByRole('alert',{}, {timeout:2500});expect(screen.queryByText('Automatisch gespeichert')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Erneut versuchen'}));await screen.findByText('Automatisch gespeichert',{}, {timeout:2500});expect(mocks.save.mock.calls[1]).toEqual(mocks.save.mock.calls[0]);});
it('holds a conflicting time until the user reviews it',async()=>{mocks.review.conflicts=[{id:'other'}];mount();fireEvent.change(screen.getByLabelText('Rückrufuhrzeit'),{target:{value:'10:30'}});await new Promise(resolve=>setTimeout(resolve,800));expect(mocks.save).not.toHaveBeenCalled();});
